### ISSUE TITLE
[epic] Data Inventory improvements for Beta-3

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/inventory.cybergreen.net#44]
*Note: this is a super issue and we will create subissues for relevant items*

* [x] Add an explanation of *key* fields e.g. Format, Taxonomy etc (could be hover, could be a key section ...)
  * [x] Create a `datapackage.json` #45 
  * [x] Add a detailed description of each field to datapackage.json @aaronkaplan  #47
  * [x] Use that information in the web page @shiweiart  #18 
* [x] Lots of UX improvements (see [this drawing](https://docs.google.com/drawings/d/1icAwrpLSHxyULFtDojnUTBGp8JnePIRH9lEWIKN52uc/edit)) #48
  * [x] Add a short explanatory description of what the data inventory is ...
* [x] Show more fields (e.g. the ones @aaronkaplan selected) (not in original SoW)
* [x] Add new field to indicate whether this is being used in cybergreen platform (and show this) #54 
* [x] Decide on `source` vs `feed` nomenclature **finally** - #2 ANS: **sources**
* [x] Display an "add a new data source" link on the main inventory page
* [x] Download button to download entire dataset (link to github directory or directly to CSV and DataPackage.json)
* [x] Rename page to Data Source Catalog

## Won't do - for future

* [ ] Add individual pages for data sources e.g. `/data-inventory/{source-id}/` (? not sure - do we need this)
  * Why? This would allow to link to individual sources by url - e.g. from stats site. Alternative is just to have a href in the page
  * We could also allow people to "edit" this data

## Specific Client Requirements

* Get full descriptions for key fields and display [on the inventory page]
* Visually mark which data sources CG is currently processing

## User Stories

As a CERT I want to see what data sources are available so that I can request them and use them in my own work
* I want to filter by particular risk types
* Taxonomy?
* What data can I get easily (e.g. publicly available or available to CERTs)

As a CERT I want to see what data sources are used in the CG stats portal so I understand what is available so that … ?? [i go visit]

As a User of the Stats portal I want to see what data is being used to build the portal so that … ??? [i know it is good quality, how detailed it is ??]

**Comment by rufuspollock** [comment]
@aaronkaplan to post list of the key fields to show.

**Comment by aaronkaplan** [comment]
understood.
agreed, @rgrp will make a sample data package and @aaronkaplan will add descriptions on key fields in the CSV/data package

**Comment by zelima** [comment]
Moving to next milestone as Still left some issues to be done

**Comment by rufuspollock** [comment]
FIXED. See https://www.cybergreen.net/data-inventory/
