### ISSUE TITLE
Search / filter sources on Data Inventory page

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/inventory.cybergreen.net#67]
As a CERT (??) I want to be able search the data sources shown in the data inventory to only show the ones i am interested in.

## Tasks

Implement in JS ...

* [x] free text search with text matching against the title of the risk (regex or simple match?)
  * [x] perform search on each keyup (live interaction)
* [x] filters for each of the metadata fields (e.g. format, public etc)
  * [x] be able to reset
  * [x] prepopulate drop-downs with list of potential values (requires us to load the data sources into JS and have a list of them)
* [x] show number of items in results

Additionally:

* [x] Additional design / ux improvements
