### ISSUE TITLE
track downloads of training materials

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/inventory.cybergreen.net#71]
We want to track downloads for PDF files on `mitigation/` and `mitigation/asean/` pages on http://www.cybergreen.net

## Acceptance criteria 

- [x] Use google analytics to track clicks on the download links (User will not need to enter any contact information)
- [x] all 4 files are tracked on both of pages 

## Tasks

- [x] ~~add goole analytics~~
- [x] add JS code for tracking downloads on `mitigation/` and `mitigation/asean/` appropriate pages

Useful reading https://support.google.com/analytics/answer/1136920?hl=en

**Comment by rufuspollock** [comment]
@zelima can you test this by downloading the materials and see if it shows up the next day in the stats.

**Comment by zelima** [comment]
@rufuspollock Downloaded, but I do not have the access to stats
